code clean-up; zloader reacts to the exit code

diff --git a/zloader b/zloader
--- a/zloader
+++ b/zloader
@@ -16,14 +16,18 @@ PLUGINS=(
 for (( i = 1 ; i <= ${#PLUGINS[@]} ; i++ )); do
 	if [ -f $PLUGINS_DIR/$PLUGINS[$i] ]; then
 		. $PLUGINS_DIR/$PLUGINS[$i]
-		if [ -n "$DEBUG" -o "$TTY[6,8]" = "tty" ]; then
-			echo "$GREEN$BOLD*$RESET $PLUGINS[$i] loaded"
+		EXITCODE=$?
+		if [ "$EXITCODE" = "0" ]; then
+			if [ -n "$DEBUG" -o "$TTY[6,8]" = "tty" ]; then
+				echo "$GREEN$BOLD*$RESET $PLUGINS[$i] loaded"
+			fi
+		else
+			echo "$RED$BOLD*$RESET $PLUGINS[$i] could not be loaded, error code: $EXITCODE"
 		fi
 	else
-		if [ -n "$DEBUG" -o "$TTY[6,8]" = "tty" ]; then
-			echo "$RED$BOLD*$RESET $PLUGINS[$i] not loaded"
-		fi
+		echo "$RED$BOLD*$RESET $PLUGINS[$i] not loaded - no such plugin"
 	fi
 done
 unset i
+unset EXITCODE
 # }}}
